development:
    adapter: redis
    url: redis://localhost:6379/1
    channel_prefix: PruebaTecnica_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://redis.example.com:7372/0
  channel_prefix: PruebaTecnica_production
